### ISSUE TITLE
Kinesis Firehose 500 Internal Failure Error

### ISSUE THREAD

**Issue by deldrid1** [electricimp/AWSKinesisFirehose#4]
https://forums.electricimp.com/discussion/4441/kinesis-firehose-500-internal-failure-error/p1

I think Hugo's fix never got put into the lib?

**Comment by hfiennes** [comment]
Just put it in, but obviously the lib version needs bumping & re-releasing.

**Comment by betzrhodes** [comment]
The issue is actually in the AWSRequestV4 library - https://github.com/electricimp/AWSRequestV4
This is where the default content type headers are set.  

AWSRequestV4 library v1.0.1 - sets content-type headers to "application/x-amz-json-1.1"
AWSRequestV4 library v1.0.2 - sets content-type headers to "application/x-amz-json-1.0" (updated for compatibility with Dynamo DB)

If you use #require "AWSRequestV4.class.nut:1.0.1" this should also fix the issue.

**Comment by hfiennes** [comment]
However, that's not workable; a customer may be using *both* services. They can't pull in different versions for each. My patch makes it work with 1.0.2 for both.

**Comment by betzrhodes** [comment]
Got it will update this library to include the correct content-header type.
